#!/bin/bash

echo "This script will help you push to GitHub"
echo "You'll need to provide your GitHub username and personal access token"
echo ""
echo "To create a personal access token:"
echo "1. Go to https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Give it a name and select 'repo' scope"
echo "4. Copy the token"
echo ""
echo "Run these commands manually:"
echo ""
echo "git push -u origin master"
echo ""
echo "When prompted:"
echo "- Username: your-github-username"
echo "- Password: your-personal-access-token (NOT your GitHub password)"
echo ""
echo "Alternatively, you can also push the cooler-ui branch:"
echo "git push origin cooler-ui"